### ISSUE TITLE
Mass distribution and hip_yaw joint limit of new Centauro model 

### ISSUE THREAD

**Issue by yangweiyou** [ADVRHumanoids/centauro-simulator#7]
I saw in the new Centauro model the battery under the pelvis was removed. Have we updated the mass of pelvis? I checked the total mass of the robot, it's the same.

Since the battery is removed, can we enlarge the joint limit of hip yaw joints, especially for the rear legs? It helps a lot for locomotion.

**Comment by nkashiri** [comment]
The battery is not removed, the battery and some other parts around pelvis are just placed differently.
Hip yaw motion ranges are not dependent on the battery placement, and therefore cannot change at the moment.

**Comment by mkamedula** [comment]
We are working to update the inertia/mass parameters, it should be done soon.

Regarding the joint limits, recently I have updated the master branch with the joint limits measured on the hardware. For the hip yaw joints, I have talked about it with Nikos and he said it may be possible, but that has to be updated on the hardware first.

**Comment by yangweiyou** [comment]
Great, glad to hear that

**Comment by ntsagarakis** [comment]
Hi Yangwei,

The battery was moved from below the pelvis to inside the pelvis.
We plan to increase the range of the hip yaw joints. As soon as this changes in the hardware we will then update also the model joint limits.
We will let you know when this will happen.

Nikos

**Comment by yangweiyou** [comment]
Thanks, Nikos. I will wait for your notification.
